steps:
  # Authenticate using service account key
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        # Write service account key to file
        echo '$$GCP_SA_KEY' > /tmp/service-account.json
        
        # Authenticate
        gcloud auth activate-service-account --key-file=/tmp/service-account.json
        gcloud config set project $$GCP_PROJECT_ID
        
        # Access secrets
        gcloud secrets versions access latest --secret=telegram-token > telegram_token.txt
        gcloud secrets versions access latest --secret=firebase-creds > firebase_creds.json
        gcloud secrets versions access latest --secret=nano-seed > nano_seed.txt

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/crypto-miner', '.']

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/crypto-miner']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'run', 'deploy', 'crypto-miniapp',
           '--image', 'gcr.io/$PROJECT_ID/crypto-miner',
           '--platform', 'managed',
           '--region', 'us-central1',
           '--allow-unauthenticated',
           '--set-env-vars=GOOGLE_CLOUD_PROJECT=$$GCP_PROJECT_ID,ENVIRONMENT=production',
           '--service-account=crypto-miner-sa@$$GCP_PROJECT_ID.iam.gserviceaccount.com']
    env:
      - 'GCP_PROJECT_ID=$_GCP_PROJECT_ID'
      - 'GCP_SA_KEY=$_GCP_SA_KEY'

# Use secrets from GitHub
substitutions:
  _GCP_PROJECT_ID: $(gcp_project_id)
  _GCP_SA_KEY: $(gcp_sa_key)

options:
  env:
    - 'GCP_PROJECT_ID=$_GCP_PROJECT_ID'
    - 'GCP_SA_KEY=$_GCP_SA_KEY'